---
version: '3'
services:
  rundeck:
    build: .

    ports:
      - "4440:4440"

    container_name: rundeck
    hostname: rundeck.exemplo.com.br
    domainname: exemplo.com.br
    dns_search: exemplo.com.br
    
    privileged: true
    restart: always

    environment:
      HOSTNAME: rundeck.exemplo.com.br
      RUNDECK_GRAILS_URL: http://127.0.0.1:4440
...
