---
# tasks file for iac-ansible-rundeck

- name: 'Instalar Dependencias'
  apt: 
    name: '{{ item }}'
    update_cache: yes 
    state: present
  with_items: 
    - 'openjdk-8-jdk'

- name: 'adicionando repositorio'
  apt_repository:
    repo: 'deb https://rundeck.bintray.com/rundeck-deb /'
    state: present
    validate_certs: no

- apt_key:
    url: 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'
    state: present
    validate_certs: no
    
#
#- name: 'Baixando .DEB Rundeck'
#  get_url: 
#    url: http://dl.bintray.com/rundeck/rundeck-deb/:rundeck_3.0.9.20181127-1.201811291844_all.deb
#    dest: /tmp/rundeck_2.10.8-1-GA_all.deb

#- name: Instalando pacote .DEB
#  apt: 
#    deb: /tmp/rundeck_2.10.8-1-GA_all.deb
...
