---
# tasks file for rundeck

- name: 'Instalar Dependencias'
  apt: 
    name: '{{ item }}'
    update_cache: yes 
    state: present
  with_items: 
    - openjdk-8-jdk
  register: DEPENDENCIA

- name: 'adicionando repositorio'
  apt_repository:
    repo: 'deb https://rundeck.bintray.com/rundeck-deb /'
    state: present
    validate_certs: no
  when: ( DEPENDENCIA is success )
  register: REPOSITORIO

- apt_key:
    url: 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'
    state: present
    validate_certs: no
  register: REPOKEY
  when: ( REPOSITORIO is success )  
    
#- name: 'Instalando Rundeck'
#  apt:
#    name: 'rundeck'
#    state: present
#    update_cache: true
#  when: ( REPOKEY is success )
...
